version: '3'

services:
  app:
    container_name: svelte_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3000"
    volumes:
      - ./static:/app/static
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "50001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./temp_db_data:/tmp/temp_db_data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
