version: '3'

services:
  app:
    container_name: svelte_app
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - DB_PORT=50001
    ports:
      - "3002:4173"
    volumes:
      - ./static:/app/static
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 50001
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:15
    restart: always
    ports:
      - "50001:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
